# Generated by Django 4.0.1 on 2022-01-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image_one',
            field=models.CharField(default='add image', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='image_three',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='image_two',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
