# Generated by Django 4.0.1 on 2022-01-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_image_one_dog_image_three_dog_image_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_three',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_two',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
